package com.nabd.ai.local.engine

import kotlinx.coroutines.flow.Flow

/**
 * LlmProvider: The primary abstraction boundary for local LLM inference.
 *
 * This contract ensures that the UI and Business Logic layers are agnostic 
 * to the underlying runtime (e.g., llama.cpp, LiteRT, or ONNX).
 */
interface LlmProvider : EngineStatus {

    /**
     * Loads a model from the specified file system path.
     * @param modelPath Absolute path to the model file (e.g., .gguf).
     * @throws IllegalStateException if the engine is not in Initialized or Unloaded state.
     */
    suspend fun loadModel(modelPath: String)

    /**
     * Starts text generation based on the provided prompt.
     * Returns a [Flow] that emits tokens as they are generated by the native layer.
     *
     * @param prompt The input text for the LLM.
     * @param grammar Optional GBNF grammar string to constrain generation.
     * @return A stream of generated tokens.
     * @throws IllegalStateException if the model is not Loaded.
     */
    fun generateText(prompt: String, grammar: String? = null): Flow<String>

    /**
     * Aborts the current generation process.
     * Transitioning to the Stopping state.
     */
    fun stopGeneration()

    /**
     * Releases all native resources and unloads the model from memory.
     */
    fun unloadModel()
}
